<a href="https://colab.research.google.com/github/sugamadhikari11/Data_Visualization_and_Model/blob/main/University.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import timeit

In [ ]:
# Load the university ranking data
data = pd.read_csv('/content/University_Dataset.csv')
data = pd.DataFrame(data)


In [ ]:
data.head()

Index                      University name Overall score Entry standards  \
0      1                  Bath Spa University           84%             37%   
1      2             University of Chichester           80%             42%   
2      3  Canterbury Christ Church University           76%             40%   
3      4       Buckinghamshire New University           78%             39%   
4      5                 Middlesex University           82%             48%   

  Student satisfaction Research quality Research intensity Graduate prospects  
0                  80%              67%                29%                 0%  
1                  75%               0%                 0%                 0%  
2                  70%               0%                 0%                49%  
3                  82%               0%                 0%                52%  
4                  80%              57%                75%                54%

In [ ]:
data = data.drop(["Overall score", "Index"], axis=1)

In [ ]:
data

University name Entry standards Student satisfaction  \
0                    Bath Spa University             37%                  80%   
1               University of Chichester             42%                  75%   
2    Canterbury Christ Church University             40%                  70%   
3         Buckinghamshire New University             39%                  82%   
4                   Middlesex University             48%                  80%   
..                                   ...             ...                  ...   
105              University of Cambridge             95%                   0%   
106                   University of Bath             73%                  84%   
107                 University of Exeter             63%                  82%   
108            Liverpool Hope University             51%                  84%   
109                  University of Leeds             71%                  77%   

    Research quality Research intensity Graduate prospects  
0                67%                29%                 0%  
1                 0%                 0%                 0%  
2                 0%                 0%                49%  
3                 0%                 0%                52%  
4                57%                75%                54%  
..               ...                ...                ...  
105              84%                93%                96%  
106              73%                96%                97%  
107              74%               100%                97%  
108              53%                88%                98%  
109              79%                83%               100%  

[110 rows x 6 columns]

In [ ]:
# Remove the percentage sign and convert numeric columns to numeric values
numeric_columns = data.columns.difference(['University name'])
data[numeric_columns] = data[numeric_columns].replace('%', '', regex=True).apply(pd.to_numeric)

# Calculate the mean of each numeric column
mean_values = data[numeric_columns].mean()

# Fill 0% values with mean respective to their own column
data[numeric_columns] = data[numeric_columns].mask(data[numeric_columns] == 0, other=mean_values, axis=1)

# Add the percentage sign back
data[numeric_columns] = data[numeric_columns].astype(int).astype(str) + '%'

# Print the updated DataFrame
data

University name Entry standards Student satisfaction  \
0                    Bath Spa University             37%                  80%   
1               University of Chichester             42%                  75%   
2    Canterbury Christ Church University             40%                  70%   
3         Buckinghamshire New University             39%                  82%   
4                   Middlesex University             48%                  80%   
..                                   ...             ...                  ...   
105              University of Cambridge             95%                  77%   
106                   University of Bath             73%                  84%   
107                 University of Exeter             63%                  82%   
108            Liverpool Hope University             51%                  84%   
109                  University of Leeds             71%                  77%   

    Research quality Research intensity Graduate prospects  
0                67%                29%                78%  
1                56%                53%                78%  
2                56%                53%                49%  
3                56%                53%                52%  
4                57%                75%                54%  
..               ...                ...                ...  
105              84%                93%                96%  
106              73%                96%                97%  
107              74%               100%                97%  
108              53%                88%                98%  
109              79%                83%               100%  

[110 rows x 6 columns]

In [ ]:
# Modify university names from 'University of [Name]' to '[Name] University'
data['University name'] = data['University name'].str.replace(r'University of (\w+)', r'\1 University')

<ipython-input-7-ed971e70c591>:2: FutureWarning: The default value of regex will change from True to False in a future version.
  data['University name'] = data['University name'].str.replace(r'University of (\w+)', r'\1 University')


#Output of Data Preperation

In [ ]:
university_data = pd.DataFrame(data)
university_data.head()

University name Entry standards Student satisfaction  \
0                  Bath Spa University             37%                  80%   
1                Chichester University             42%                  75%   
2  Canterbury Christ Church University             40%                  70%   
3       Buckinghamshire New University             39%                  82%   
4                 Middlesex University             48%                  80%   

  Research quality Research intensity Graduate prospects  
0              67%                29%                78%  
1              56%                53%                78%  
2              56%                53%                49%  
3              56%                53%                52%  
4              57%                75%                54%

In [ ]:
# Convert percentage strings to float for calculations
for column in university_data.columns[1:]:
  university_data[column + '_calc'] = university_data[column].astype(str).str.rstrip('%').astype('float') / 100.0


In [ ]:
print(university_data)

                         University name Entry standards Student satisfaction  \
0                    Bath Spa University             37%                  80%   
1                  Chichester University             42%                  75%   
2    Canterbury Christ Church University             40%                  70%   
3         Buckinghamshire New University             39%                  82%   
4                   Middlesex University             48%                  80%   
..                                   ...             ...                  ...   
105                 Cambridge University             95%                  77%   
106                      Bath University             73%                  84%   
107                    Exeter University             63%                  82%   
108            Liverpool Hope University             51%                  84%   
109                     Leeds University             71%                  77%   

    Research quality Resear

In [ ]:
# Define the criteria
criteria = ['Student satisfaction', 'Graduate prospects', 'Research quality', 'Research intensity', 'Entry standards']

# Print a menu for the user
print("Please select the order of criteria by entering the corresponding numbers, separated by commas:")
for i, criterion in enumerate(criteria, 1):
    print(f"{i}. {criterion}")

# Get the user's selection
user_selection = input()

# Convert the user's selection to a list of integers
user_order = [int(num) for num in user_selection.split(',')]

# Assert that the user's selection is within the valid range
assert all(1 <= num <= len(criteria) for num in user_order), "Invalid selection"

# Create the order of criteria for calculations based on the user's selection
criteria_order_calc = [criteria[i-1] + '_calc' for i in user_order]

# Assert that all criteria are included in the calculation order
assert all(criterion + '_calc' in criteria_order_calc for criterion in criteria), "Not all criteria included in calculation order"


Please select the order of criteria by entering the corresponding numbers, separated by commas:
1. Student satisfaction
2. Graduate prospects
3. Research quality
4. Research intensity
5. Entry standards
2,3,1,5,4


In [ ]:
print(criteria_order_calc)


['Graduate prospects_calc', 'Research quality_calc', 'Student satisfaction_calc', 'Entry standards_calc', 'Research intensity_calc']


In [ ]:
# Pairwise Comparisons
comparison_matrix = university_data[criteria_order_calc].values


In [ ]:
print(comparison_matrix)

[[0.8  0.78 0.67 0.29 0.37]
 [0.75 0.78 0.56 0.53 0.42]
 [0.7  0.49 0.56 0.53 0.4 ]
 [0.82 0.52 0.56 0.53 0.39]
 [0.8  0.54 0.57 0.75 0.48]
 [0.77 0.59 0.69 0.63 0.51]
 [0.77 0.61 0.7  1.   0.54]
 [0.77 0.61 0.58 0.57 0.42]
 [0.85 0.63 0.56 0.53 0.48]
 [0.8  0.63 0.54 0.23 0.51]
 [0.75 0.63 0.63 0.3  0.46]
 [0.78 0.64 0.41 0.11 0.33]
 [0.69 0.64 0.56 0.53 0.43]
 [0.82 0.65 0.51 0.38 0.39]
 [0.78 0.66 0.55 0.38 0.52]
 [0.77 0.66 0.56 0.53 0.44]
 [0.76 0.66 0.59 0.22 0.61]
 [0.78 0.68 0.56 0.53 0.46]
 [0.75 0.68 0.58 0.24 0.59]
 [0.8  0.69 0.51 0.3  0.55]
 [0.8  0.69 0.38 0.17 0.47]
 [0.78 0.69 0.56 0.53 0.42]
 [0.86 0.7  0.65 0.22 0.44]
 [0.81 0.7  0.55 0.31 0.52]
 [0.88 0.71 0.33 0.8  0.47]
 [0.76 0.71 0.56 0.53 0.51]
 [0.75 0.71 0.67 0.28 0.53]
 [0.86 0.73 0.53 0.15 0.44]
 [0.83 0.73 0.32 0.38 0.58]
 [0.83 0.73 0.56 0.53 0.44]
 [0.76 0.73 0.67 0.6  0.53]
 [0.76 0.73 0.51 0.33 0.48]
 [0.76 0.73 0.56 0.53 0.53]
 [0.75 0.73 0.43 0.38 0.47]
 [0.81 0.74 0.6  0.63 0.52]
 [0.8  0.74 0.56 0.5

In [ ]:
def calculate_criterion_weights():
    # Calculate the weights of the criteria based on pairwise comparisons
    row_sums = comparison_matrix.sum(axis=1)
    col_sums = comparison_matrix.sum(axis=0)

    criterion_weights = []
    for i in range(len(col_sums)):
        criterion_weight = float(row_sums[i]) / float(col_sums[i])
        criterion_weights.append(criterion_weight)

    # Normalize the weights
    sum_weights = sum(criterion_weights)
    criterion_weights = [weight / sum_weights for weight in criterion_weights]

    # Assert that the sum of weights is 1 (or very close to 1 due to floating point precision)
    assert abs(sum(criterion_weights) - 1) < 1e-6, "Sum of weights is not 1"

    return criterion_weights

def calculate_university_scores(criterion_weights):
    # Perform weighted sum calculations for each university based on criterion weights
    university_scores = []
    for i in range(len(university_data)):
        university_score_elements = []
        for j in range(len(criterion_weights)):
            print(f"university_data.iloc[{i}, {j+1}]: {university_data.iloc[i, j+1]}")
            print(f"criterion_weights[{j}]: {criterion_weights[j]}")
            element = float(university_data.iloc[i, j+1].rstrip('%')) / 100.0 * criterion_weights[j]
            university_score_elements.append(element)
        university_score = sum(university_score_elements)
        university_scores.append(university_score)

    # Assert that all scores are between 0 and 1
    assert all(0 <= score <= 1 for score in university_scores), "Some scores are not between 0 and 1"

    # Update the university_data DataFrame with the overall scores
    university_data['Overall score'] = university_scores


In [ ]:

criterion_weights = calculate_criterion_weights()
print(criterion_weights)

calculate_university_scores(criterion_weights)
print(university_data)

[0.16659509485285562, 0.2159122733167865, 0.1560471542170543, 0.2257278805390007, 0.23571759707430284]
university_data.iloc[0, 1]: 37%
criterion_weights[0]: 0.16659509485285562
university_data.iloc[0, 2]: 80%
criterion_weights[1]: 0.2159122733167865
university_data.iloc[0, 3]: 67%
criterion_weights[2]: 0.1560471542170543
university_data.iloc[0, 4]: 29%
criterion_weights[3]: 0.2257278805390007
university_data.iloc[0, 5]: 78%
criterion_weights[4]: 0.23571759707430284
university_data.iloc[1, 1]: 42%
criterion_weights[0]: 0.16659509485285562
university_data.iloc[1, 2]: 75%
criterion_weights[1]: 0.2159122733167865
university_data.iloc[1, 3]: 56%
criterion_weights[2]: 0.1560471542170543
university_data.iloc[1, 4]: 53%
criterion_weights[3]: 0.2257278805390007
university_data.iloc[1, 5]: 78%
criterion_weights[4]: 0.23571759707430284
university_data.iloc[2, 1]: 40%
criterion_weights[0]: 0.16659509485285562
university_data.iloc[2, 2]: 70%
criterion_weights[1]: 0.2159122733167865
university_data.

In [ ]:
# Convert the overall score to percentage
university_data['Overall score'] = (university_data['Overall score'] * 100).astype(int)

# Append a '%' sign to the score
university_data['Overall score'] = university_data['Overall score'].astype(str) + '%'

# Drop the temporary columns that end with '_calc'
university_data = university_data.drop(columns=[col for col in university_data.columns if col.endswith('_calc')])

# Print the updated DataFrame
print(university_data)


                         University name Entry standards Student satisfaction  \
0                    Bath Spa University             37%                  80%   
1                  Chichester University             42%                  75%   
2    Canterbury Christ Church University             40%                  70%   
3         Buckinghamshire New University             39%                  82%   
4                   Middlesex University             48%                  80%   
..                                   ...             ...                  ...   
105                 Cambridge University             95%                  77%   
106                      Bath University             73%                  84%   
107                    Exeter University             63%                  82%   
108            Liverpool Hope University             51%                  84%   
109                     Leeds University             71%                  77%   

    Research quality Resear

#Output after Calculating overall socre


In [ ]:
print(university_data)

                         University name Entry standards Student satisfaction  \
0                    Bath Spa University             37%                  80%   
1                  Chichester University             42%                  75%   
2    Canterbury Christ Church University             40%                  70%   
3         Buckinghamshire New University             39%                  82%   
4                   Middlesex University             48%                  80%   
..                                   ...             ...                  ...   
105                 Cambridge University             95%                  77%   
106                      Bath University             73%                  84%   
107                    Exeter University             63%                  82%   
108            Liverpool Hope University             51%                  84%   
109                     Leeds University             71%                  77%   

    Research quality Resear

In [ ]:
# Convert DataFrame to dictionary
university_dict = university_data.to_dict('records')
print(university_dict)

[{'University name': 'Bath Spa University', 'Entry standards': '37%', 'Student satisfaction': '80%', 'Research quality': '67%', 'Research intensity': '29%', 'Graduate prospects': '78%', 'Overall score': '58%'}, {'University name': 'Chichester University', 'Entry standards': '42%', 'Student satisfaction': '75%', 'Research quality': '56%', 'Research intensity': '53%', 'Graduate prospects': '78%', 'Overall score': '62%'}, {'University name': 'Canterbury Christ Church University', 'Entry standards': '40%', 'Student satisfaction': '70%', 'Research quality': '56%', 'Research intensity': '53%', 'Graduate prospects': '49%', 'Overall score': '54%'}, {'University name': 'Buckinghamshire New University', 'Entry standards': '39%', 'Student satisfaction': '82%', 'Research quality': '56%', 'Research intensity': '53%', 'Graduate prospects': '52%', 'Overall score': '57%'}, {'University name': 'Middlesex University', 'Entry standards': '48%', 'Student satisfaction': '80%', 'Research quality': '57%', 'R

In [ ]:
# Convert DataFrame to dictionary
university_dict = university_data.to_dict('records')

# Assert that the conversion was successful
assert isinstance(university_dict, list), "Failed to convert DataFrame to dictionary"

# Convert 'Graduate prospects' values to integers or floats
for univ in university_dict:
    univ['Graduate prospects'] = int(univ['Graduate prospects'].rstrip('%'))


In [ ]:
# Merge Sort
def merge_sort(univ_list, criteria):
    # Assert that the criteria is in the university data
    assert all(criteria in univ for univ in univ_list), "Criteria not in university data"

    if len(univ_list) <= 1:
        return univ_list

    mid = len(univ_list) // 2
    left_half = univ_list[:mid]
    right_half = univ_list[mid:]

    # Assert that the list was split correctly
    assert len(left_half) + len(right_half) == len(univ_list), "Failed to split list correctly"

    return merge(merge_sort(left_half, criteria), merge_sort(right_half, criteria), criteria)

def merge(left, right, criteria):
    merged = []
    left_index = 0
    right_index = 0

    # Merge smaller elements first
    while left_index < len(left) and right_index < len(right):
        if left[left_index][criteria] > right[right_index][criteria]:
            merged.append(left[left_index])
            left_index += 1
        elif left[left_index][criteria] < right[right_index][criteria]:
            merged.append(right[right_index])
            right_index += 1
        else:  # If the criteria values are equal
            if left[left_index]['University name'] < right[right_index]['University name']:
                merged.append(left[left_index])
                left_index += 1
            else:
                merged.append(right[right_index])
                right_index += 1

    # If there are remaining elements in left or right half, append them to the result
    while left_index < len(left):
        merged.append(left[left_index])
        left_index += 1

    while right_index < len(right):
        merged.append(right[right_index])
        right_index += 1

    return merged


# Hash-based Search
def hash_search(univ_list, target):
    univ_dict = {univ['University name']: univ for univ in univ_list}

    # Assert that the target university is in the data
    assert target in univ_dict, "Target university not found"

    return univ_dict.get(target, None)



In [ ]:
# User Interaction for University Search
while True:
    print("Welcome to University Ranking")
    print("Please choose an option:")
    print("1. Display the ranking of all universities")
    print("2. Search for a specific university")
    print("3. Exit")
    option = input("Enter the selection between 1 or 2 or 3: ")

    # Assert that the user's input is a valid option
    assert option in ['1', '2', '3'], "Invalid option"

    if option == '1':
        print("Please enter the criteria you want to sort by:")
        criteria_input = input()
        # Convert the input to the desired format
        criteria_input = criteria_input.lower().capitalize()
        print("Searching for university...")



        start_time = timeit.default_timer()
        # Sort the universities
        sorted_universities = merge_sort(university_dict, criteria_input)

        # Record the ending time
        end_time = timeit.default_timer()

        # Calculate the execution time in seconds
        execution_time = end_time - start_time


        # Print or store the execution time
        print(f"Execution time: {execution_time} seconds")

        # Print the ranking of all universities
        for i, univ in enumerate(sorted_universities):
            if criteria_input == 'Graduate prospects':
                print(f"Rank {i+1}: {univ['University name']} - {criteria_input}: {univ[criteria_input]}%")
            else:
                print(f"Rank {i+1}: {univ['University name']} - {criteria_input}: {univ[criteria_input]}")
    elif option == '2':
        print("Please enter the name of a university you want to search for:")
        university_name_input = input()
        # Convert the input to the desired format
        university_name_input = university_name_input.title()
        print("Please enter the criteria you want to sort by:")
        criteria_input = input()
        # Convert the input to the desired format
        criteria_input = criteria_input.lower().capitalize()
        print("Searching for university...")

        # Sort the universities
        sorted_universities = merge_sort(university_dict, criteria_input)

        # Search for a university
        result = hash_search(sorted_universities, university_name_input)

        # Assert that the search result is correct
        assert result is None or result['University name'] == university_name_input, "Search result is incorrect"

        # Print the result in the original format with overall score in percentage
        if result:
            rank = sorted_universities.index(result) + 1
            print(f"The rank and overall score of {university_name_input} is:")
            print(f"Rank: {rank}")
            print(f"University name: {result['University name']}")
            print(f"Entry standards: {result['Entry standards']}")
            print(f"Student satisfaction: {result['Student satisfaction']}")
            print(f"Research quality: {result['Research quality']}")
            print(f"Research intensity: {result['Research intensity']}")
            print(f"Graduate prospects: {result['Graduate prospects']}%")
            print(f"Overall score: {result['Overall score']}")
        else:
            print("University not found.")
    elif option == '3':
        break
    else:
        print("Invalid option. Please try again.")



Welcome to University Ranking
Please choose an option:
1. Display the ranking of all universities
2. Search for a specific university
3. Exit
Please enter the criteria you want to sort by:
Searching for university...
Execution time: 0.0007017720000703775 seconds
Rank 1: Cambridge University - Overall score: 89%
Rank 2: Imperial College London - Overall score: 88%
Rank 3: Bath University - Overall score: 86%
Rank 4: Durham University - Overall score: 86%
Rank 5: Glasgow University - Overall score: 86%
Rank 6: Oxford University - Overall score: 86%
Rank 7: St University Andrews - Overall score: 86%
Rank 8: Edinburgh University - Overall score: 85%
Rank 9: Exeter University - Overall score: 85%
Rank 10: Birmingham University - Overall score: 84%
Rank 11: Bristol University - Overall score: 84%
Rank 12: King's College London - Overall score: 84%
Rank 13: Manchester University - Overall score: 84%
Rank 14: Aberystwyth University - Overall score: 83%
Rank 15: Leeds University - Overall score

In [ ]:
#Alternative
# Quick Sort
def quick_sort(univ_list, criteria):
    if len(univ_list) <= 1:
        return univ_list

    pivot_index = len(univ_list) // 2
    pivot = univ_list[pivot_index]

    # Split the list into two sub-arrays based on the pivot
    left = [univ for univ in univ_list if univ[criteria] > pivot[criteria]]
    middle = [univ for univ in univ_list if univ[criteria] == pivot[criteria]]
    right = [univ for univ in univ_list if univ[criteria] < pivot[criteria]]

    # Recursively sort the sub-arrays and combine the results
    return quick_sort(left, criteria) + middle + quick_sort(right, criteria)


# Linear Search
def linear_search(univ_list, target):
    for univ in univ_list:
        if univ['University name'] == target:
            return univ
    return None


# User Interaction for University Search
while True:
    print("Welcome to University Ranking")
    print("Please choose an option:")
    print("1. Display the ranking of all universities")
    print("2. Search for a specific university")
    print("3. Exit")
    option = input("Enter the selection between 1 or 2 or 3: ")

    # Assert that the user's input is a valid option
    assert option in ['1', '2', '3'], "Invalid option"

    if option == '1':
        print("Please enter the criteria you want to rank by:")
        criteria_input = input()
        # Convert the input to the desired format
        criteria_input = criteria_input.lower().capitalize()
        print("Ranking universities...")

        # Sort the universities based on the specified criteria
        sorted_universities = quick_sort(university_dict, criteria_input)

        execution_time = timeit.timeit(lambda: quick_sort(university_dict, criteria_input), number=1)

        # Print or store the execution time
        print(f"Execution time: {execution_time} seconds")

        # Print the ranking of all universities
        for i, univ in enumerate(sorted_universities):
            if criteria_input == 'Graduate prospects':
                print(f"Rank {i+1}: {univ['University name']} - {criteria_input}: {univ[criteria_input]}%")
            else:
                print(f"Rank {i+1}: {univ['University name']} - {criteria_input}: {univ[criteria_input]}")
    elif option == '2':
        print("Please enter the name of a university you want to search for:")
        university_name_input = input()
        # Convert the input to the desired format
        university_name_input = university_name_input.title()
        print("Please enter the criteria you want to rank by:")
        criteria_input = input()
        # Convert the input to the desired format
        criteria_input = criteria_input.lower().capitalize()
        print("Searching for university...")

        # Sort the universities based on the specified criteria
        sorted_universities = quick_sort(university_dict, criteria_input)

        # Search for the university
        result = linear_search(sorted_universities, university_name_input)

        if result:
            rank = sorted_universities.index(result) + 1
            print(f"The rank and overall score of {university_name_input} based on {criteria_input} is:")
            print(f"Rank: {rank}")
            print(f"University name: {result['University name']}")
            print(f"Entry standards: {result['Entry standards']}")
            print(f"Student satisfaction: {result['Student satisfaction']}")
            print(f"Research quality: {result['Research quality']}")
            print(f"Research intensity: {result['Research intensity']}")
            print(f"Graduate prospects: {result['Graduate prospects']}%")
            print(f"Overall score: {result['Overall score']}")
        else:
            print("University not found.")
    elif option == '3':
        break



Welcome to University Ranking
Please choose an option:
1. Display the ranking of all universities
2. Search for a specific university
3. Exit
Enter the selection between 1 or 2 or 3: 1
Please enter the criteria you want to rank by:
overall score
Ranking universities...
Execution time: 0.0003212139999959618 seconds
Rank 1: Cambridge University - Overall score: 89%
Rank 2: Imperial College London - Overall score: 88%
Rank 3: Oxford University - Overall score: 87%
Rank 4: Glasgow University - Overall score: 86%
Rank 5: Durham University - Overall score: 86%
Rank 6: Edinburgh University - Overall score: 85%
Rank 7: St University Andrews - Overall score: 85%
Rank 8: Bath University - Overall score: 85%
Rank 9: Manchester University - Overall score: 84%
Rank 10: Bristol University - Overall score: 84%
Rank 11: King's College London - Overall score: 84%
Rank 12: Birmingham University - Overall score: 84%
Rank 13: Exeter University - Overall score: 84%
Rank 14: Southampton University - Overall

KeyboardInterrupt: ignored